language: python
python:
- '2.7'
- '3.6'
install:
- pip install -e ./
env: TEST1="python -m unittest testing" TEST2="echo ok"
jobs:
  include:
    python: '3.6'
    install:
    - pip install mypy
    - pip install black
    env:
    - TEST1="black --check ."
    - TEST2="mypy pyhike"
script:
- "$TEST1"
- "$TEST2"
deploy:
  provider: pypi
  skip_existing: true
  user: internetimagery
  password:
    secure: t4LnxN8hUlhfH1r04v/hlxg2gv4QgP6aeNYB1LYsKXl+K+RfNJmq3Nh4zemoSarf3nqMHExcpa5kd0210lSfSLGNI9TsVIFgf+iKcKyZU4gWGGbYExtG0CfRc7H2UG1dTuph71cr8jDjqPhvhnl/iPe+d3oPyW9Jf9iBYETBwbscMUDUNFwgKMQ9ebWEYdN9Y5cMhtYR5Nj6lqA8DdpAkitGYKlIdjxfD9cs4T1dG/6PtA/sniUGgMJ6TUTwvrIoQUq843fzKcdWSsSaW51MHzZs+v2JtaBShzQeQ7yMKeCYTaOl9KpL/1U5gMHnSBrvtWFvJ2x3Jgd1s/MD+43Sr76X8sjdOf3awS0j/09ahQ9ehSV2a5MvSAsux2R21uWKc+cWyP/Fz1fTYY0WV2L89KNt9pon1U8j0U4ZQStZrezQwDYh2flflmu/8E2+Vj+qT1hu+MJncFoo/1HbXYsWDUtSiuwHlhFYH80nE2rF912k6I8iLQw+T4lL72dLJj/QiXz2nks8XU5HoyBB12ee0HZbUUiRBfl9u9v60CyNXc3RvXFzNp5bwHEIkdZbN+KQ+XenkRSLRqau4i2qeCC/zHaXcospkHS4czdiJFFntzE2chuYHF4s14CYUpyPXUrA0DoUQgQpvgvWNXN+rDPvMVOD5hxLkn7O15VrBwELLbE=
  on:
    tags: true
