
language: python
python:
- '2.7'
- '3.6'
install:
# Install current working version
- pip install -e ./
env:
  TEST1="python -m unittest testing"
  TEST2="echo ok"
jobs:
  include:
    python: '3.6'
    install:
    - pip install mypy
    - pip install black
    env:
    - TEST1="black --check ."
    - TEST2="mypy pyhike"
script:
- $TEST1
- $TEST2