
language: python
python:
- '2.7'
- '3.6'
install:
# Install current working version
- pip install -e ./
env:
  TEST="python -m unittest testing"
jobs:
  include:
    python: '3.6'
    install:
    - pip install mypy
    - pip install black
    env:
    - TEST="black --check . && mypy pyhike"
script:
- $TEST