
language: python
python:
- '2.7'
- '3.6'
install:
# Install current working version
- pip install -e ./
env:
  TEST1="python -m unittest testing"
  TEST2="echo ok"
jobs:
  include:
    python: '3.6'
    install:
    - pip install mypy
    - pip install black
    env:
    - TEST1="black --check ."
    - TEST2="mypy pyhike"
script:
- $TEST1
- $TEST2

deploy:
  provider: pypi
  skip_existing: true
  user: internetimagery
  password:
    secure: hu6V5SJByekEGK7bwYrLKODCSYFFdtTHQEAvh6oe/6EBqgy0aHUUUBgS1FpNSf49rLoBPbk+aKKyuWfjBcOz8HCwx7VXvQjdHNxNOkwf1Pah/fpq/dLHucN7hWIW9B1s5HGtERqKusQ6FeIign8I/vLuo+ja9FJFRyWOUex0mTVoezstTtbNAGV0uX5UzU5lOFNpJ3kTkCac9BeL5sFhbM/C1XPT9CVgOObh81WgKBd+AofFCd6DZWTeXHfbzWP1T9FgYJLGJ9mmuL4pIVo1rpP9uSx87ARKJzblH7ahvY5zLtmQi7x3O9rywEWpAEQD2/pm6AG55uEzg9ym6Fexo81Opa/ptroJp3vfTdxpRTJHEc60H+m6Z0pbImXkWVSVQPHIePYT6COQCmxKUYhprXNbTUUlwyG1EkOotCGUhHqhb8gtSoZioIfwNvPLszEavZyEO/Rtd0Xj/VmK0Z/V0qITLsKrTAKm0f80kYkrgCCgTBNrhxu+WQ5FtuicJzIsTyqAxkofUbS7b3vmtsrIfsACoPOuwAnkaWmVYzjukPI5h8Dcmws7jwkBRO9TJct+XX9FiUxARwIj7qMGIYH/aLk7NoevBpQu9gJgkenz1jbzMz6E97PHwXMeebA0Sz/IZ0EuNIvrCDZbozJxve1En5uVDnXw/NezowA4v5MvaZY=
  on:
      tags: true